from rest_framework.routers import DefaultRouter
from .views import PhototypeExecuteProjectPrepareViewset, PhototypeExecuteProjectDevelopViewset, PhototypeExecuteProjectViewset, \
    PhototypeExecuteProjectDetailsPrepareViewset, PhototypeExecuteProjectDetailsViewset, PTEFilesViewset, \
    PhototypeExecuteProjectDetailsMakeViewset, PhototypeExecuteProjectDetailsPurchaseViewset


phototypeexecuteproject_router = DefaultRouter()
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteprojectprepare', PhototypeExecuteProjectPrepareViewset, basename='phototypeexecuteprojectprepare')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteprojectdevelop', PhototypeExecuteProjectDevelopViewset, basename='phototypeexecuteprojectdevelop')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteproject', PhototypeExecuteProjectViewset, basename='phototypeexecuteproject')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteprojectdetailsprepare', PhototypeExecuteProjectDetailsPrepareViewset, basename='phototypeexecuteprojectdetailsprepare')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteprojectdetailsmake', PhototypeExecuteProjectDetailsMakeViewset, basename='phototypeexecuteprojectdetailsmake')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteprojectdetailspurchase', PhototypeExecuteProjectDetailsPurchaseViewset, basename='phototypeexecuteprojectdetailspurchase')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/phototypeexecuteprojectdetails', PhototypeExecuteProjectDetailsViewset, basename='phototypeexecuteprojectdetails')
phototypeexecuteproject_router.register(r'project/phototypeexecuteproject/ptefiles', PTEFilesViewset, basename='ptefiles')

